// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 8.0.17_20200923091552 by TAF Team.
// Generated from `./MingNodeServer.jce'
// **********************************************************************

/* eslint-disable */

var MingApp = require('./MingNodeServer.js').MingApp;
module.exports.MingApp = MingApp;

MingApp.MingNodeServerImp.prototype.initialize = function ( ) {
    //TODO::

}

MingApp.MingNodeServerImp.prototype.mingHello = function (current, s, r) {
    // 业务处理
    r = s;
    current.sendResponse(0, r);
}


